apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include "minioconfig" . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: minioconfig
          secret:
            secretName: {{ template "fullname" . }}
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
        {{ end }}
      containers:
      - name: minio
        image: minio/minio:RELEASE.2018-05-11T00-29-24Z
        args:
        - server
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - --config-dir /mnt/{{ .Values.persistentStorage.existingClaimName }}/.minio
        - /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ else }}
        - --config-dir /tmp/.minio
        - /tmp
        {{ end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9000
        securityContext:
          runAsUser: 999
          # supplementalGroups:
          # - 999
        env:
        - name: TZ
          value: Europe/Oslo
        volumeMounts:
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: minioconfig
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}/.minio
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
        {{ else }}
        - name: minioconfig
          mountPath: /tmp/.minio
        {{ end }}
