apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  config.json: {{ include "minioconfig" . | b64enc }}
